/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DialogAddToCart: typeof import('./../components/DialogAddToCart.vue')['default']
    DialogAddToWishList: typeof import('./../components/DialogAddToWishList.vue')['default']
    DialogQuickView: typeof import('./../components/DialogQuickView.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
